# ---
# name: Build Push Image

# on:
#   push:
#     branches:
#       - "develop"

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: '0'
#       # - name: Set up QEMU
#       #   uses: docker/setup-qemu-action@v1
#       # - name: Set up Docker Buildx
#       #   uses: docker/setup-buildx-action@v1
#       # - name: Login to DockerHub
#       #   uses: docker/login-action@v1
#       #   with:
#       #     username: ${{ secrets.DOCKERHUB_USERNAME }}
#       #     password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Bump version and push tag
#         uses: anothrNick/github-tag-action@1.36.0
#         env:
#           GITHUB_TOKEN: ${{ secrets.PUSH_TAG_GITHUB_TOKEN }}
#           WITH_V: false
#           DEFAULT_BUMP: patch
#       - name: Print output
#         run: |
#           echo ${{ steps.tag-bump.outputs.new_tag }}
#       # - name: Build and push
#       #   uses: docker/build-push-action@v2
#       #   with:
#       #     context: .
#       #     push: true
#       #     tags: apurvdeodhar/my_devops_demos:${{ steps.tag-bump.outputs.new_tag }}
