name: build

on:
  push:
    branches:
      - 'main'

# jobs:
#   build:
#     name: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Get the tag
#         id: get-tag
#         run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
#       - name: Print tag
#         run: |
#           echo $tag
jobs:
  generate:
    runs-on: ubuntu-latest
    name: get tag
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Print tag
        run: |
          echo ${{ steps.previoustag.outputs.tag }}

      # - name: 'Create new milestone'
      #   id: createmilestone
      #   uses: "WyriHaximus/github-action-create-milestone@v1"
      #   with:
      #     title: ${{ steps.semvers.outputs.patch }}
      #   env:
      #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
