name: build

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print from build
        run: |
          echo "This is from build"
          hadolint --help
