name: build

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get the tag
        id: get-tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Print tag
        run: |
          echo $tag
