name: Get bump tag

on:
  push:
    branches:
      - "develop"

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      - name: Bump release version
        id: bump_version
        uses: cookbenjamin/update-version@v1.0.1
        with:
          current-version: '${{ steps.previoustag.outputs.tag }}'
          increment-version-fragment: 'PATCH'
          prerelease-fragment: 'BETA'
      - name: Do something with your bumped release version
        run: |
          echo ${{ steps.bump_version.outputs.next-version }}
